name: Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test
  
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [runTests]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
